# Generated by Django 3.2.9 on 2021-11-18 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
    ]
